"""Refuse to train unless the corpus, splits, and test quarantine are all intact.

Run before every training launch. Exit 0 = safe to train, non-zero = do not train.

The expensive check is corpus integrity. This repo ships metadata only (~8MB); the
1.3GB image corpus is regenerated by scripts/download_unified_datasets.py. Filenames
encode dataset enumeration order, so a regenerated corpus that does not match the
committed splits would silently train on the wrong images — or on the quarantined
test set. That is a hard failure here, with the recovery command printed.

CLI: python scripts/preflight.py [--quick]
"""

import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.utils import REPO_ROOT  # noqa: E402

SPLITS = REPO_ROOT / "data" / "splits_unified"
REBUILD = (
    "  python scripts/download_unified_datasets.py\n"
    "  python scripts/map_trashnet_provenance.py\n"
    "  python -m src.unified_data --build-splits"
)


class Check:
    def __init__(self):
        self.failed = []

    def __call__(self, name: str, ok: bool, detail: str = "") -> bool:
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}{f' — {detail}' if detail else ''}")
        if not ok:
            self.failed.append(name)
        return ok


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--quick", action="store_true",
                    help="skip the 11k-file existence scan (use only between runs)")
    args = ap.parse_args()
    check = Check()

    print("Environment:")
    try:
        import timm
        import torch
        device = ("cuda" if torch.cuda.is_available()
                  else "mps" if torch.backends.mps.is_available() else "cpu")
        check("deps import", True, f"torch {torch.__version__}, timm {timm.__version__}")
        check("accelerator", device != "cpu", f"{device}"
              + (" — training on CPU is not viable" if device == "cpu" else ""))
    except ImportError as exc:
        check("deps import", False, str(exc))
        print("\nInstall first: pip install -r requirements.txt")
        return 1

    print("\nSplits:")
    needed = ["groups.csv", "folds.csv", "test.csv", "quarantine.csv"]
    if not check("split files present", all((SPLITS / f).exists() for f in needed),
                 str(SPLITS)):
        print(f"\nRebuild with:\n{REBUILD}")
        return 1

    groups = pd.read_csv(SPLITS / "groups.csv")
    folds = pd.read_csv(SPLITS / "folds.csv")
    test = pd.read_csv(SPLITS / "test.csv")
    quarantine = set(pd.read_csv(SPLITS / "quarantine.csv")["path"])

    check("arithmetic: kept = trainval + test", len(groups) == len(folds) + len(test),
          f"{len(groups)} = {len(folds)} + {len(test)}")
    check("paths unique", folds["path"].is_unique and test["path"].is_unique)
    check("train/test path-disjoint", not (set(folds["path"]) & set(test["path"])))
    check("train/test group-disjoint", not (set(folds["group"]) & set(test["group"])))
    check("no group spans folds", (folds.groupby("group")["fold"].nunique() == 1).all())

    print("\nSpent-test quarantine:")
    check("no quarantined image in train/val", not (quarantine & set(folds["path"])),
          f"{len(quarantine)} images tracked")
    check("all quarantined images held in test", quarantine <= set(test["path"]))

    print("\nCorpus:")
    if args.quick:
        print("  [SKIP] file existence scan (--quick)")
    else:
        missing = [p for p in groups["path"] if not (REPO_ROOT / p).exists()]
        ok = check("every split path exists on disk", not missing,
                   f"{len(groups) - len(missing)}/{len(groups)} present")
        if not ok:
            print(f"\n  {len(missing)} files missing, e.g. {missing[:2]}")
            print("  The corpus does not match the committed splits. Either it was never")
            print("  downloaded, or an upstream dataset changed. Regenerate everything:")
            print(f"{REBUILD}")

    print("\nModel:")
    try:
        from src.model import build_model
        build_model({"model": "convnextv2_tiny.fcmae_ft_in22k_in1k"}, pretrained=False)
        check("backbone builds under the 30M cap", True)
    except Exception as exc:  # noqa: BLE001 — any failure here blocks training
        check("backbone builds under the 30M cap", False, f"{type(exc).__name__}: {exc}")

    if check.failed:
        print(f"\nPREFLIGHT FAILED: {len(check.failed)} check(s) — {', '.join(check.failed)}")
        print("Do not train until these pass.")
        return 1
    print("\nPREFLIGHT PASSED — safe to train.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
