"""Keep reports/champion.json pointing at the best model trained so far.

Run after every experiment. It derives everything from the append-only experiments.csv
plus the deterministic checkpoint layout, so it is safe to run at any time and always
produces the right answer — including after a crash or an interrupted run.

The point: this project may be stopped at any moment. Whoever picks it up reads
champion.json and has a usable model, without reading a single training log.

Ranking is macro-F1 first (the corpus is imbalanced — `trash` is the smallest class),
accuracy as tie-break.

CLI: python scripts/update_champion.py [--top N]
"""

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.utils import EXPERIMENTS_CSV, REPO_ROOT  # noqa: E402

CHAMPION = REPO_ROOT / "reports" / "champion.json"
LEADERBOARD = REPO_ROOT / "reports" / "LEADERBOARD.md"


def numeric(series):
    return pd.to_numeric(series, errors="coerce")


def splits_dir_of(config_json: str) -> str:
    try:
        return json.loads(config_json).get("splits_dir", "")
    except (TypeError, ValueError):
        return ""


def collect(splits_dir: str) -> pd.DataFrame:
    if not EXPERIMENTS_CSV.exists():
        return pd.DataFrame()
    df = pd.read_csv(EXPERIMENTS_CSV)
    df = df[df["stage"] == "train"].copy()
    if df.empty:
        return df
    # experiments.csv is append-only and spans both corpora. A run on the old 2.5k
    # TrashNet splits is not comparable to one on the 11.3k unified splits, so mixing
    # them would crown a champion trained on a different problem.
    before = len(df)
    df = df[df["config_json"].map(splits_dir_of) == splits_dir]
    if before - len(df):
        print(f"Ignoring {before - len(df)} run(s) from other splits (want {splits_dir}).")
    if df.empty:
        return df
    df["macro_f1"] = numeric(df["val_macro_f1"])
    df["val_acc"] = numeric(df["best_val_acc"])
    df = df.dropna(subset=["macro_f1"])
    # Checkpoint layout is deterministic (see train_run), so it need not be logged.
    df["checkpoint"] = df.apply(
        lambda r: f"checkpoints/{r['run_name']}/fold{int(r['fold']) if str(r['fold']).strip() else 0}/best.pth",
        axis=1)
    df["exists"] = df["checkpoint"].map(lambda p: (REPO_ROOT / p).exists())
    return df.sort_values(["macro_f1", "val_acc"], ascending=False)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--top", type=int, default=10)
    ap.add_argument("--splits-dir", default="data/splits_unified",
                    help="only rank runs trained on these splits")
    args = ap.parse_args()

    df = collect(args.splits_dir)
    if df.empty:
        print(f"No completed training runs on {args.splits_dir} yet — nothing to rank.")
        return 0

    usable = df[df["exists"]]
    if usable.empty:
        print(f"{len(df)} run(s) logged but no checkpoint files found on disk.")
        print("Checkpoints are gitignored — they do not travel with the repo.")
        return 1

    best = usable.iloc[0]
    CHAMPION.parent.mkdir(parents=True, exist_ok=True)
    CHAMPION.write_text(json.dumps({
        "run_name": str(best["run_name"]),
        "model": str(best["model"]),
        "img_size": int(best["img_size"]) if pd.notna(best["img_size"]) else None,
        # str() throughout: pandas hands back numpy scalars, which json cannot encode.
        "fold": str(best["fold"]),
        "checkpoint": str(best["checkpoint"]),
        "val_macro_f1": round(float(best["macro_f1"]), 6),
        "val_accuracy": round(float(best["val_acc"]), 6),
        "per_class_recall": json.loads(best["per_class_recall"] or "{}"),
        "timestamp": str(best["timestamp"]),
        "config_hash": str(best["config_hash"]),
        "note": "Best validation macro-F1 so far. Test set NOT consulted for this choice.",
    }, indent=2) + "\n")

    rows = usable.head(args.top)
    lines = ["# Leaderboard", "",
             "Auto-generated by `scripts/update_champion.py` from experiments.csv.",
             "Ranked by validation macro-F1. The test set plays no part in this ranking.", "",
             "| rank | run | model | img | fold | macro-F1 | val acc |",
             "|---:|---|---|---:|---:|---:|---:|"]
    for i, (_, r) in enumerate(rows.iterrows(), start=1):
        lines.append(f"| {i} | {r['run_name']} | `{r['model']}` | {r['img_size']} | "
                     f"{r['fold']} | {r['macro_f1']:.4f} | {r['val_acc']:.4f} |")
    missing = len(df) - len(usable)
    if missing:
        lines += ["", f"_{missing} logged run(s) omitted: checkpoint file absent._"]
    LEADERBOARD.write_text("\n".join(lines) + "\n")

    print(f"Champion: {best['run_name']} (fold {best['fold']}) "
          f"macro-F1 {best['macro_f1']:.4f}, val acc {best['val_acc']:.4f}")
    print(f"  {best['checkpoint']}")
    print(f"Wrote {CHAMPION.relative_to(REPO_ROOT)} and {LEADERBOARD.relative_to(REPO_ROOT)} "
          f"({len(usable)} usable of {len(df)} runs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
